CREATE TABLE `cleanblog`.`users` (`id` INT NOT NULL AUTO_INCREMENT , `email` VARCHAR(200) NOT NULL , `username` VARCHAR(100) NOT NULL , `password` VARCHAR(200) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `cleanblog`.`posts` (`id` INT NOT NULL AUTO_INCREMENT , `title` VARCHAR(200) NOT NULL , `subtitle` VARCHAR(200) NOT NULL , `body` TEXT NOT NULL , `image` VARCHAR(100) NOT NULL , `user_id` VARCHAR(3) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `cleanblog`.`categories` (`id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(100) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
